import { jsPDF } from 'jspdf';
import { FitnessPlan, UserProfile } from '@/types/fitness';

export const exportToPDF = (plan: FitnessPlan, profile: UserProfile | null) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = 20;
  const lineHeight = 7;
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;

  // Helper functions
  const addTitle = (text: string, size: number = 16) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', 'bold');
    doc.text(text, margin, yPos);
    yPos += lineHeight + 3;
  };

  const addText = (text: string, size: number = 10) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(text, contentWidth);
    doc.text(lines, margin, yPos);
    yPos += lines.length * lineHeight;
  };

  const addSection = (title: string) => {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }
    yPos += 5;
    doc.setFillColor(20, 184, 166);
    doc.rect(margin, yPos - 5, contentWidth, 10, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(title, margin + 5, yPos + 2);
    doc.setTextColor(0, 0, 0);
    yPos += 15;
  };

  const checkPageBreak = (requiredSpace: number) => {
    if (yPos + requiredSpace > 280) {
      doc.addPage();
      yPos = 20;
    }
  };

  // Header
  doc.setFillColor(20, 184, 166);
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('FitGenius AI', margin, 25);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Your Personalized Fitness Plan', margin, 35);
  doc.setTextColor(0, 0, 0);
  yPos = 55;

  // User Info
  if (profile) {
    addSection('Your Profile');
    addText(`Name: ${profile.name}`);
    addText(`Age: ${profile.age} | Gender: ${profile.gender}`);
    addText(`Height: ${profile.height} cm | Weight: ${profile.weight} kg`);
    addText(`Goal: ${profile.fitnessGoal.replace('_', ' ')} | Level: ${profile.fitnessLevel}`);
    addText(`Location: ${profile.workoutLocation} | Diet: ${profile.dietaryPreference.replace('_', ' ')}`);
  }

  // Motivational Quote
  yPos += 5;
  doc.setFillColor(245, 245, 245);
  doc.rect(margin, yPos, contentWidth, 20, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  const quoteLines = doc.splitTextToSize(`"${plan.motivationalQuote}"`, contentWidth - 10);
  doc.text(quoteLines, margin + 5, yPos + 8);
  yPos += 30;

  // Workout Plan
  addSection('Weekly Workout Plan');
  
  plan.workoutPlan.forEach((day) => {
    checkPageBreak(50);
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`${day.day} - ${day.focus}`, margin, yPos);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(`Duration: ${day.duration} | Calories: ${day.caloriesBurned}`, margin + 100, yPos);
    yPos += lineHeight;

    day.exercises.forEach((exercise) => {
      checkPageBreak(15);
      doc.setFontSize(10);
      doc.text(`• ${exercise.name}: ${exercise.sets} sets x ${exercise.reps} (${exercise.restTime} rest)`, margin + 5, yPos);
      yPos += lineHeight;
    });
    
    yPos += 3;
  });

  // Diet Plan
  doc.addPage();
  yPos = 20;
  addSection('Daily Diet Plan');

  const meals = [
    { type: 'Breakfast', meal: plan.dietPlan.breakfast },
    { type: 'Morning Snack', meal: plan.dietPlan.morningSnack },
    { type: 'Lunch', meal: plan.dietPlan.lunch },
    { type: 'Evening Snack', meal: plan.dietPlan.eveningSnack },
    { type: 'Dinner', meal: plan.dietPlan.dinner },
  ];

  meals.forEach(({ type, meal }) => {
    checkPageBreak(40);
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(type, margin, yPos);
    yPos += lineHeight;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(meal.name, margin + 5, yPos);
    yPos += lineHeight;

    doc.setFontSize(9);
    doc.text(`Calories: ${meal.calories} | Protein: ${meal.protein} | Carbs: ${meal.carbs} | Fats: ${meal.fats}`, margin + 5, yPos);
    yPos += lineHeight;

    doc.text(`Ingredients: ${meal.ingredients.join(', ')}`, margin + 5, yPos);
    yPos += lineHeight + 5;
  });

  // Tips
  checkPageBreak(60);
  addSection('AI Tips & Recommendations');
  
  plan.tips.forEach((tip, index) => {
    checkPageBreak(15);
    addText(`${index + 1}. ${tip}`);
  });

  // Summary
  checkPageBreak(40);
  yPos += 10;
  addSection('Plan Summary');
  addText(plan.summary);

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Generated by FitGenius AI | Page ${i} of ${pageCount}`,
      pageWidth / 2,
      290,
      { align: 'center' }
    );
  }

  // Save
  doc.save(`FitGenius_Plan_${profile?.name || 'User'}.pdf`);
};
